### PR TITLE
Specify Deploy Config

### PR DESCRIPTION
**Pull request by donavon**
Adds a `--config` command line option to specify the deploy config file. It defaults to `_config-deploy.yml` for backward compatibility, but you can specify any file that you wish. See updated README for details.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.9`

**Comment by yegor256** [comment]
@donavon thanks for your contribution! Version 1.9 is in RubyGems.

**Pull request merged**
