### PR TITLE
Update README.md for dead link to jgd blog

### PR DESCRIPTION
**Pull request by wilsonmar**

### CODE REVIEW

**Comment by davvd** [comment]
@wilsonmar Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by danbernier** [comment]
Hah, I was _just_ about to make this same exact PR. Thanks @wilsonmar!

**Comment by yegor256** [comment]
@wilsonmar thanks!

**Comment by davvd** [comment]
@yegor256 done, I added **16 mins** in payment `000-84c02b3d`, 142 hours and 28 mins spent to complete this; review comments (c=1) added as a bonus; +16 added to your rating, at the moment it is: [+1756](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
