### PR TITLE
Support Jekyll Drafts

### PR DESCRIPTION
**Pull request by donavon**
The PR adds a `--drafts` command line option that will be passed on to the Jekyll build. I have the use case for doing a draft build for an "internal" blog, but push the non-draft build externally.

If approved, could you please merge and publish a `v1.11` as soon as possible? Thx.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jekyll-github-deploy#28` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @donavon, total is [+15](http://www.0crat.com/u/donavon).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.11`

**Comment by yegor256** [comment]
@donavon done, thanks for your contribution!

**Pull request merged**
